"""LangGraph state model for agent workflow."""

from enum import Enum
from typing import Any, Dict, List, Optional, TypedDict

from pydantic import BaseModel


class ProjectPhase(str, Enum):
    """Project development phases."""

    INITIALIZATION = "initialization"
    REQUIREMENT_ANALYSIS = "requirement_analysis"
    ARCHITECTURE_DESIGN = "architecture_design"
    CODING = "coding"
    DEBUGGING = "debugging"
    TESTING = "testing"
    DOCUMENTATION = "documentation"
    DEPLOYMENT = "deployment"
    COMPLETED = "completed"
    FAILED = "failed"


class AgentDecision(BaseModel):
    """Agent decision and rationale."""

    agent_name: str
    decision: str
    rationale: str
    confidence: float
    timestamp: str


class CodeArtifact(BaseModel):
    """Code artifact generated by agents."""

    file_path: str
    content: str
    language: str
    agent: str
    timestamp: str


class TestArtifact(BaseModel):
    """Test artifact generated by testing agent."""

    file_path: str
    content: str
    test_type: str
    coverage: Optional[float] = None
    agent: str
    timestamp: str


class DocumentationArtifact(BaseModel):
    """Documentation artifact."""

    doc_type: str  # README, API_DOCS, ARCHITECTURE, etc.
    content: str
    agent: str
    timestamp: str


class RAGContext(BaseModel):
    """RAG retrieval context."""

    knowledge_base_results: List[Dict[str, Any]] = []
    project_memory_results: List[Dict[str, Any]] = []
    version_results: List[Dict[str, Any]] = []


class AgentState(TypedDict, total=False):
    """Shared state passed between agents in LangGraph workflow.

    This state is maintained throughout the entire agent workflow and
    contains all project information, artifacts, and decisions.
    """

    # Project Metadata
    project_id: str
    project_name: str
    project_description: str
    user_requirements: str

    # Workflow State
    current_phase: str  # Store as string for JSON compatibility
    current_agent: str
    next_agent: Optional[str]
    phase_history: List[str]  # Store as list of strings

    # Agent Outputs
    requirements_analysis: Optional[Dict[str, Any]]
    architecture_design: Optional[Dict[str, Any]]
    code_artifacts: List[Dict[str, Any]]  # Store as dicts for JSON compatibility
    test_artifacts: List[Dict[str, Any]]
    documentation_artifacts: List[Dict[str, Any]]
    deployment_config: Optional[Dict[str, Any]]

    # Agent Decisions
    agent_decisions: List[Dict[str, Any]]  # Store as dicts for JSON compatibility

    # RAG Context
    rag_context: Dict[str, Any]  # Store as dict for JSON compatibility

    # Error Handling
    errors: List[Dict[str, Any]]
    retry_count: int
    max_retries: int

    # Metadata
    created_at: str
    updated_at: str
    completed: bool

