/**
 * Generator for Documentation
 */
window.DocsGenerator = {
   generate: (config) => {
      // Dynamic Resource Naming
      const resName = config.resourceName || 'Item';
      const resNamePlural = resName.toLowerCase() + 's';

      const readme = `# ${config.name}

Generated by CollabMind.

## Overview
${config.name} is a full-stack application generated to meet your requirements. 
It includes a modern frontend, a robust FastAPI backend, and a SQLite database.

## Project Structure
- **frontend/**: HTML/CSS/JS client application.
- **backend/**: Python FastAPI server with REST endpoints.
- **database/**: SQL scripts and database files.

## Setup Instructions

### Backend
1. Navigate to the \`backend\` directory:
   \`\`\`bash
   cd backend
   \`\`\`
2. Create a virtual environment:
   \`\`\`bash
   python -m venv venv
   source venv/bin/activate  # On Windows: venv\\Scripts\\activate
   \`\`\`
3. Install dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`
4. Run the server:
   \`\`\`bash
   uvicorn main:app --reload
   \`\`\`
   The API will be available at http://localhost:8000.
   API Docs (Swagger UI) at http://localhost:8000/docs.

### Frontend
1. Open \`frontend/index.html\` in your browser.
2. Ensure the backend is running for full functionality.

## Features
- **Authentication**: JWT-based login and registration.
- **Resource Management**: Create, Read, Update, and Delete **${resNamePlural}**.
- **Responsive UI**: Optimized for mobile and desktop.
## Troubleshooting
58: 
59: ### "Windows protected your PC" Warning
60: If you see a blue window preventing \`run_windows.bat\` from starting:
61: 1. Click **"More info"**.
62: 2. Click **"Run anyway"**.
63: *Note: This happens because the script was downloaded from the internet. It is safe to run.*
64: 
65: ### "File Blocked" Warning
66: If the file is completely blocked:
67: 1. Right-click \`run_windows.bat\`.
68: 2. Select **Properties**.
69: 3. Check **"Unblock"** at the bottom.
70: 4. Click **Apply** and try again.
71: `;
      return {
         'README.md': readme
      };
   }
};
